import { ProductType, CartType } from "@/types";
export const userData = {
  name: "Alexandar Morgan",
  email: "alex.morgan@example.com",
  avatar: "/avatar/man.jpg", // Placeholder for avatar
  shippingAddresses: [
    {
      id: "addr1",
      name: "Home",
      street: "123 Cyber Street",
      city: "Neo City",
      state: "CA",
      zipCode: "90210",
      country: "USA",
      isDefault: true
    },
    {
      id: "addr2",
      name: "Work",
      street: "456 Digital Avenue",
      city: "Neo City",
      state: "CA",
      zipCode: "90211",
      country: "USA",
      isDefault: false
    }
  ]
};

export const orderHistory = [
  {
    id: "order123",
    date: "April 10, 2025",
    status: "Delivered",
    total: 249.95,
    products: [
      {
        id: "8",
        name: "Gaming Mouse G502",
        images: ["/products/8/1.jpg", "/products/8/2.jpg"],
        price: 79,
        originalPrice: null,
        rating: 4.7,
        reviewCount: 2300,
        onSale: false,
        quantity: 2,
      },
      {
        id: "11",
        name: "Logitech Gaming Headset",
        images: ["/products/11/1.jpg", "/products/11/2.jpg"],
        price: 99,
        originalPrice: 119,
        rating: 4.6,
        reviewCount: 1100,
        onSale: true,
        quantity: 1,
      },
    ]
  },
  {
    id: "order456",
    date: "March 25, 2025",
    status: "Delivered",
    total: 178.50,
    products: [
      {
        id: "1",
        name: "PlayStation 5",
        images: ["/products/1/1.jpg", "/products/1/2.jpg"],
        price: 499,
        originalPrice: 549,
        rating: 4.0,
        reviewCount: 300,
        onSale: false,
        label: "Best Seller",
      },
      {
        id: "20",
        name: "Gaming Desk Mat",
        images: ["/products/20/1.jpg"],
        price: 29,
        originalPrice: null,
        rating: 4.7,
        reviewCount: 56,
        onSale: true
      }
    ]
  }
];

export const relatedCart: ProductType[] = [
  {
    id: "7",
    name: "Gaming Backpack",
    price: 49,
    shortDescription: "Perfect for carrying gaming gear",
    description: "Spacious and stylish gaming-themed backpack.",
    images: ["/products/7/1.jpg", "/products/7/2.jpg"],
    category: "merch",
    brand: "logitech",
    rating: 4.5,
    reviewCount: 620,
    sku: "LGT-MRC-007",
    stockQuantity: 150,
    onSale: true,
    originalPrice: 59,
    createdAt: "2024-01-10T10:10:00Z",
    colors: ["Black", "Grey"],
  },
  {
    id: "9",
    name: "Asus ROG Zephyrus",
    price: 899,
    originalPrice: 1999,
    shortDescription: "High-end gaming laptop",
    description: "Powerful RTX laptop with Ryzen processor.",
    images: ["/products/9/1.jpg", "/products/9/2.jpg", "/products/9/3.jpg"],
    category: "pc",
    brand: "asus",
    rating: 4.6,
    reviewCount: 1450,
    sku: "ASUS-PC-009",
    stockQuantity: 25,
    onSale: true,
    createdAt: "2024-02-01T09:00:00Z",
    specifications: [
      { name: "GPU", value: "RTX 4080" },
      { name: "RAM", value: "32GB" },
    ],
  },
  {
    id: "14",
    name: "PS5 Controller",
    price: 69,
    shortDescription: "DualSense wireless controller",
    description: "Haptic feedback and adaptive triggers.",
    images: ["/products/14/1.jpg", "/products/14/2.jpg"],
    category: "accessories",
    brand: "sony",
    rating: 4.8,
    reviewCount: 3900,
    sku: "SNY-ACC-014",
    stockQuantity: 120,
    onSale: false,
    createdAt: "2024-04-01T10:00:00Z",
    colors: ["White", "Red"],
  },
];

export const cart: CartType[] = [
  {
    id: "1",
    name: "PlayStation 5",
    images: ["/products/1/1.jpg", "/products/1/2.jpg"],
    price: 499,
    originalPrice: 549,
    rating: 4.8,
    reviewCount: 3200,
    onSale: true,
    quantity: 1,
  },
  {
    id: "8",
    name: "Gaming Mouse G502",
    images: ["/products/8/1.jpg", "/products/8/2.jpg"],
    price: 79,
    originalPrice: null,
    rating: 4.7,
    reviewCount: 2300,
    onSale: false,
    quantity: 2,
  },
  {
    id: "15",
    name: "Xbox Wireless Controller",
    images: ["/products/15/1.jpg", "/products/15/2.jpg"],
    price: 64,
    originalPrice: 74,
    rating: 4.5,
    reviewCount: 2500,
    onSale: true,
    quantity: 1,
  },
  {
    id: "11",
    name: "Logitech Gaming Headset",
    images: ["/products/11/1.jpg", "/products/11/2.jpg"],
    price: 99,
    originalPrice: 119,
    rating: 4.6,
    reviewCount: 1100,
    onSale: true,
    quantity: 1,
  },
];

export const products: ProductType[] = [
  {
    id: "1",
    name: "PlayStation 5",
    price: 499,
    originalPrice: 549,
    shortDescription: "Next-gen console by Sony",
    description:
      "Experience lightning-fast loading with an ultra-high speed SSD and deeper immersion.",
    images: ["/products/1/1.jpg", "/products/1/2.jpg"],
    category: "console",
    brand: "sony",
    rating: 4.8,
    reviewCount: 3200,
    sku: "PS5-SNY-001",
    stockQuantity: 45,
    onSale: true,
    createdAt: "2024-04-01T10:00:00Z",
    specifications: [{ name: "Storage", value: "1TB" }],
    colors: ["White", "Black"],
    label: "Best Seller",
  },
  {
    id: "2",
    name: "Xbox Series X",
    price: 499,
    originalPrice: 529,
    shortDescription: "Powerful gaming console by Xbox",
    description:
      "Play thousands of titles from four generations of consoles with backward compatibility.",
    images: ["/products/2/1.jpg"],
    category: "console",
    brand: "xbox",
    rating: 4.7,
    reviewCount: 2800,
    sku: "XBX-XSX-002",
    stockQuantity: 60,
    onSale: true,
    createdAt: "2024-03-15T09:30:00Z",
    specifications: [{ name: "Storage", value: "1TB SSD" }],
    colors: ["Black"],
  },
  {
    id: "3",
    name: "Nintendo Switch OLED",
    price: 349,
    shortDescription: "Portable and home console hybrid",
    description: "Enjoy vivid gaming on the go or docked to your TV.",
    images: ["/products/3/1.jpg", "/products/3/2.jpg","/products/3/3.jpg"], 
    category: "console",
    brand: "nintendo",
    rating: 4.6,
    reviewCount: 1500,
    sku: "NNTD-SWT-003",
    stockQuantity: 30,
    onSale: false,
    createdAt: "2024-02-20T12:00:00Z",
    specifications: [{ name: "Display", value: "7-inch OLED" }],
    colors: ["White", "Neon Red/Blue"],
  },
  {
    id: "4",
    name: "Retro NES Classic",
    price: 69,
    shortDescription: "Classic NES console remake",
    description:
      "Play nostalgic 8-bit games on the original NES style console.",
    images: ["/products/4/1.jpg", "/products/4/2.jpg"],
    category: "gear",
    brand: "nintendo",
    rating: 4.3,
    reviewCount: 850,
    sku: "NNTD-NES-004",
    stockQuantity: 90,
    onSale: false,
    createdAt: "2024-01-18T14:30:00Z",
    label: "Limited Edition",
  },
  {
    id: "5",
    name: "The Last of Us Part II",
    price: 59,
    shortDescription: "Survival game from Naughty Dog",
    description: "Emotional story-driven gameplay in a post-apocalyptic world.",
    images: ["/products/5/1.jpg", "/products/5/2.jpg"],
    category: "games",
    brand: "sony",
    rating: 4.9,
    reviewCount: 4300,
    sku: "SONY-GME-005",
    stockQuantity: 200,
    onSale: false,
    createdAt: "2024-03-01T11:00:00Z",
    sizes: ["Standard", "Collector's"],
    label: "New Arrival",
  },
  {
    id: "6",
    name: "Halo Infinite",
    price: 59,
    shortDescription: "Flagship Xbox shooter title",
    description: "Master Chief returns in a gripping new adventure.",
    images: ["/products/6/1.jpg", "/products/6/2.jpg"],
    category: "games",
    brand: "xbox",
    rating: 4.2,
    reviewCount: 1700,
    sku: "XBX-GME-006",
    stockQuantity: 180,
    onSale: false,
    createdAt: "2024-03-22T08:00:00Z",
  },
  {
    id: "7",
    name: "Gaming Backpack",
    price: 49,
    shortDescription: "Perfect for carrying gaming gear",
    description: "Spacious and stylish gaming-themed backpack.",
    images: ["/products/7/1.jpg", "/products/7/2.jpg"],
    category: "merch",
    brand: "logitech",
    rating: 4.5,
    reviewCount: 620,
    sku: "LGT-MRC-007",
    stockQuantity: 150,
    onSale: true,
    originalPrice: 59,
    createdAt: "2024-01-10T10:10:00Z",
    colors: ["Black", "Grey"],
  },
  {
    id: "8",
    name: "Gaming Mouse G502",
    price: 79,
    shortDescription: "Precision gaming mouse",
    description: "Logitech G502 with customizable weights and RGB.",
    images: ["/products/8/1.jpg", "/products/8/2.jpg"],
    category: "accessories",
    brand: "logitech",
    rating: 4.7,
    reviewCount: 2300,
    sku: "LGT-ACC-008",
    stockQuantity: 210,
    onSale: false,
    createdAt: "2024-04-05T13:00:00Z",
    specifications: [{ name: "DPI", value: "16000" }],
  },
  {
    id: "9",
    name: "Asus ROG Zephyrus",
    price: 899,
    originalPrice: 999,
    shortDescription: "High-end gaming laptop",
    description: "Powerful RTX laptop with Ryzen processor.",
    images: ["/products/9/1.jpg", "/products/9/2.jpg", "/products/9/3.jpg"],
    category: "pc",
    brand: "asus",
    rating: 4.6,
    reviewCount: 1450,
    sku: "ASUS-PC-009",
    stockQuantity: 25,
    onSale: true,
    createdAt: "2024-02-01T09:00:00Z",
    specifications: [
      { name: "GPU", value: "RTX 4080" },
      { name: "RAM", value: "32GB" },
    ],
  },
  {
    id: "10",
    name: "HP Omen 16",
    price: 799,
    shortDescription: "Solid gaming experience",
    description: "Balanced performance with great thermals.",
    images: ["/products/10/1.jpg", "/products/10/2.jpg", "/products/10/3.jpg","/products/10/4.jpg"],
    category: "pc",
    brand: "hp",
    rating: 4.4,
    reviewCount: 980,
    sku: "HP-PC-010",
    stockQuantity: 35,
    onSale: false,
    createdAt: "2024-01-20T12:30:00Z",
  },

  {
    id: "11",
    name: "Logitech Gaming Headset",
    price: 99,
    shortDescription: "Surround sound for immersive gaming",
    description: "Clear mic and excellent soundstage for esports.",
    images: ["/products/11/1.jpg", "/products/11/2.jpg"],
    category: "accessories",
    brand: "logitech",
    rating: 4.6,
    reviewCount: 1100,
    sku: "LGT-ACC-011",
    stockQuantity: 100,
    onSale: true,
    originalPrice: 119,
    createdAt: "2024-04-10T15:00:00Z",
  },
  {
    id: "12",
    name: "Lenovo Legion 7",
    price: 999,
    shortDescription: "Gaming powerhouse laptop",
    description: "AI-optimized performance with 165Hz display.",
    images: ["/products/12/1.jpg", "/products/12/2.jpg"],
    category: "pc",
    brand: "lenovo",
    rating: 4.3,
    reviewCount: 670,
    sku: "LNV-PC-012",
    stockQuantity: 40,
    onSale: false,
    createdAt: "2024-03-28T17:00:00Z",
  },
  {
    id: "13",
    name: "Mario Kart Deluxe 8",
    price: 59,
    shortDescription: "Arcade-style racing game",
    description: "Race your friends in this fun-filled classic.",
    images: ["/products/13/1.jpg"],
    category: "games",
    brand: "nintendo",
    rating: 4.9,
    reviewCount: 5100,
    sku: "NNTD-GME-013",
    stockQuantity: 95,
    onSale: false,
    createdAt: "2024-02-10T11:00:00Z",
  },
  {
    id: "14",
    name: "PS5 Controller",
    price: 69,
    shortDescription: "DualSense wireless controller",
    description: "Haptic feedback and adaptive triggers.",
    images: ["/products/14/1.jpg", "/products/14/2.jpg"],
    category: "accessories",
    brand: "sony",
    rating: 4.8,
    reviewCount: 3900,
    sku: "SNY-ACC-014",
    stockQuantity: 120,
    onSale: false,
    createdAt: "2024-04-01T10:00:00Z",
    colors: ["White", "Red"],
  },
  {
    id: "15",
    name: "Xbox Wireless Controller",
    price: 64,
    shortDescription: "Official Xbox controller",
    description: "Ergonomic and responsive design.",
    images: ["/products/15/1.jpg", "/products/15/2.jpg"],
    category: "accessories",
    brand: "xbox",
    rating: 4.5,
    reviewCount: 2500,
    sku: "XBX-ACC-015",
    stockQuantity: 130,
    onSale: true,
    originalPrice: 74,
    createdAt: "2024-04-03T11:00:00Z",
  },
  {
    id: "16",
    name: "GameBoy",
    price: 79,
    shortDescription: "Iconic 8-bit handheld console by Nintendo",
    description: "The Game Boy is an 8-bit handheld gaming console developed and released by Nintendo in 1989. It became a cultural icon due to its compact design, long battery life, and an impressive library of games",
    images: ["/products/16/1.jpg"],
    category: "gear",
    brand: "nintendo",
    rating: 4.2,
    reviewCount: 900,
    sku: "NNTD-GER-016",
    stockQuantity: 80,
    onSale: false,
    createdAt: "2024-01-02T10:00:00Z",
  },
  {
    id: "17",
    name: "Gaming T-Shirt",
    price: 25,
    shortDescription: "Stylish gaming-themed shirt",
    description: "Show your passion with this high-quality shirt.",
    images: ["/products/17/1.png"],
    category: "merch",
    brand: "asus",
    rating: 4.1,
    reviewCount: 410,
    sku: "ASUS-MRC-017",
    stockQuantity: 250,
    onSale: true,
    originalPrice: 30,
    createdAt: "2024-04-12T08:30:00Z",
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "19",
    name: "Gaming Chair",
    price: 249,
    shortDescription: "Comfortable gaming chair",
    description: "Ergonomic design for long gaming sessions.",
    images: ["/products/19/1.jpg", "/products/19/2.jpg"],
    category: "accessories",
    brand: "lenovo",
    rating: 4.6,
    reviewCount: 780,
    sku: "LNV-ACC-019",
    stockQuantity: 50,
    onSale: true,
    originalPrice: 279,
    createdAt: "2024-04-14T14:30:00Z",
  },
  {
    id: "20",
    name: "Gaming Desk Mat",
    price: 29,
    shortDescription: "Large mouse pad",
    description: "Provides a smooth surface and aesthetic.",
    images: ["/products/20/1.jpg"],
    category: "accessories",
    brand: "logitech",
    rating: 4.7,
    reviewCount: 640,
    sku: "LGT-ACC-020",
    stockQuantity: 300,
    onSale: false,
    createdAt: "2024-02-15T09:00:00Z",
  },
];
